on: push
name: CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: tests
      uses: cedrickring/golang-action@1.5.2
      with:
        args: make test
          
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
