on: push
name: CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
    - name: tests
      run: |
        make test
          
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
